name: certora-verification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install python
        uses: actions/setup-python@v2
        with: { python-version: 3.9 }

      - name: Install java
        uses: actions/setup-java@v1
        with: { java-version: "11", java-package: jre }

      - name: Install certora cli
        run: pip3 install certora-cli==7.3.0

      - name: Install solc
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.23/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.23

      - name: Verify
        run: |
          certoraRun certora/confs/${{ matrix.contract }}
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}

    strategy:
      fail-fast: false
      max-parallel: 16
      matrix:
        contract:
          - MinterGateway.conf
          - ContinuousIndexingMath.conf
          - MinterGateway-r01-only-activateMinter.conf
          - MinterGateway-r01-only-cancelMint.conf
          - MinterGateway-r01-only-freezeMinter.conf
          - MinterGateway-r01-only-proposeMint.conf
          - MinterGateway-r01-only-proposeRetrieval.conf
          - MinterGateway-r01-only-updateCollateral.conf
          - MinterGateway-r01-only-updateIndex.conf
